---

- name: Setup Guacamole
  hosts: guacamole_hosts
  vars:
    apt_requirements:
      - python3
      - python3-pip

    terminalserver_containers:
      - ts-desktop1

  roles:
    - role: mboehm21.guacamole_rdp
